class StudentRunner
{
 public static void main(String args[])
 {
     Student student = new Student();
     System.out.println(student.getName());
     student.setName("Rahul");
     System.out.println(student.getName());
     System.out.println(student.getFees());
     student.setFees(50000.2f);
     System.out.println(student.getFees());
     student.setRollNumber(101);
     System.out.println(student.getRollNumber());
     student.setCourse("Computer Science");
     System.out.println(student.getCourse());
     student.setPercentage(87.3f);
     System.out.println(student.getPercentage());
     student.setSemester("4th Semester");
     System.out.println(student.getSemester());
     student.setScholarship(15000.0f);
     System.out.println(student.getScholarship());

     Student student1 = new Student();
     System.out.println(student1.getName());
     student1.setName("Anjali");
     System.out.println(student1.getName());
     System.out.println(student1.getFees());
     student1.setFees(48000.0f);
     System.out.println(student1.getFees());
     student1.setRollNumber(102);
     System.out.println(student1.getRollNumber());
     student1.setCourse("Electronics");
     System.out.println(student1.getCourse());
     student1.setPercentage(91.2f);
     System.out.println(student1.getPercentage());
     student1.setSemester("4th Semester");
     System.out.println(student1.getSemester());
     student1.setScholarship(16000.0f);
     System.out.println(student1.getScholarship());

     Student student2 = new Student();
     System.out.println(student2.getName());
     student2.setName("Kiran");
     System.out.println(student2.getName());
     System.out.println(student2.getFees());
     student2.setFees(47000.0f);
     System.out.println(student2.getFees());
     student2.setRollNumber(103);
     System.out.println(student2.getRollNumber());
     student2.setCourse("Mechanical");
     System.out.println(student2.getCourse());
     student2.setPercentage(76.5f);
     System.out.println(student2.getPercentage());
     student2.setSemester("4th Semester");
     System.out.println(student2.getSemester());
     student2.setScholarship(14000.0f);
     System.out.println(student2.getScholarship());

     Student student3 = new Student();
     System.out.println(student3.getName());
     student3.setName("Sneha");
     System.out.println(student3.getName());
     System.out.println(student3.getFees());
     student3.setFees(51000.0f);
     System.out.println(student3.getFees());
     student3.setRollNumber(104);
     System.out.println(student3.getRollNumber());
     student3.setCourse("Civil");
     System.out.println(student3.getCourse());
     student3.setPercentage(83.7f);
     System.out.println(student3.getPercentage());
     student3.setSemester("4th Semester");
     System.out.println(student3.getSemester());
     student3.setScholarship(13000.0f);
     System.out.println(student3.getScholarship());

     Student student4 = new Student();
     System.out.println(student4.getName());
     student4.setName("Vikram");
     System.out.println(student4.getName());
     System.out.println(student4.getFees());
     student4.setFees(52000.0f);
     System.out.println(student4.getFees());
     student4.setRollNumber(105);
     System.out.println(student4.getRollNumber());
     student4.setCourse("IT");
     System.out.println(student4.getCourse());
     student4.setPercentage(88.0f);
     System.out.println(student4.getPercentage());
     student4.setSemester("4th Semester");
     System.out.println(student4.getSemester());
     student4.setScholarship(12000.0f);
     System.out.println(student4.getScholarship());

     Student student5 = new Student();
     System.out.println(student5.getName());
     student5.setName("Neha");
     System.out.println(student5.getName());
     System.out.println(student5.getFees());
     student5.setFees(49000.0f);
     System.out.println(student5.getFees());
     student5.setRollNumber(106);
     System.out.println(student5.getRollNumber());
     student5.setCourse("Biotech");
     System.out.println(student5.getCourse());
     student5.setPercentage(85.5f);
     System.out.println(student5.getPercentage());
     student5.setSemester("4th Semester");
     System.out.println(student5.getSemester());
     student5.setScholarship(12500.0f);
     System.out.println(student5.getScholarship());

     Student student6 = new Student();
     System.out.println(student6.getName());
     student6.setName("Tarun");
     System.out.println(student6.getName());
     System.out.println(student6.getFees());
     student6.setFees(53000.0f);
     System.out.println(student6.getFees());
     student6.setRollNumber(107);
     System.out.println(student6.getRollNumber());
     student6.setCourse("MBA");
     System.out.println(student6.getCourse());
     student6.setPercentage(89.4f);
     System.out.println(student6.getPercentage());
     student6.setSemester("4th Semester");
     System.out.println(student6.getSemester());
     student6.setScholarship(17000.0f);
     System.out.println(student6.getScholarship());

     Student student7 = new Student();
     System.out.println(student7.getName());
     student7.setName("Divya");
     System.out.println(student7.getName());
     System.out.println(student7.getFees());
     student7.setFees(49500.0f);
     System.out.println(student7.getFees());
     student7.setRollNumber(108);
     System.out.println(student7.getRollNumber());
     student7.setCourse("Fashion Design");
     System.out.println(student7.getCourse());
     student7.setPercentage(92.1f);
     System.out.println(student7.getPercentage());
     student7.setSemester("4th Semester");
     System.out.println(student7.getSemester());
     student7.setScholarship(18000.0f);
     System.out.println(student7.getScholarship());

     Student student8 = new Student();
     System.out.println(student8.getName());
     student8.setName("Arjun");
     System.out.println(student8.getName());
     System.out.println(student8.getFees());
     student8.setFees(55000.0f);
     System.out.println(student8.getFees());
     student8.setRollNumber(109);
     System.out.println(student8.getRollNumber());
     student8.setCourse("Architecture");
     System.out.println(student8.getCourse());
     student8.setPercentage(86.0f);
     System.out.println(student8.getPercentage());
     student8.setSemester("4th Semester");
     System.out.println(student8.getSemester());
     student8.setScholarship(16000.0f);
     System.out.println(student8.getScholarship());

     Student student9 = new Student();
     System.out.println(student9.getName());
     student9.setName("Meena");
     System.out.println(student9.getName());
     System.out.println(student9.getFees());
     student9.setFees(47000.0f);
     System.out.println(student9.getFees());
     student9.setRollNumber(110);
     System.out.println(student9.getRollNumber());
     student9.setCourse("English Literature");
     System.out.println(student9.getCourse());
     student9.setPercentage(90.3f);
     System.out.println(student9.getPercentage());
     student9.setSemester("4th Semester");
     System.out.println(student9.getSemester());
     student9.setScholarship(19000.0f);
     System.out.println(student9.getScholarship());
 }
}
