class VehicleRunner
{
 public static void main(String args[])
 {
     Vehicle vehicle=new Vehicle();
     System.out.println(vehicle.getName());
     vehicle.setName("Toyata");
     System.out.println(vehicle.getName());
     System.out.println(vehicle.getPrice());
     vehicle.setPrice(500000.2f);
     System.out.println(vehicle.getPrice());
     vehicle.setCapacity(4000);
     System.out.println(vehicle.getCapacity());
     vehicle.setFeatures("4x4");
     System.out.println(vehicle.getFeatures());
     vehicle.setMilage(12.3f);
     System.out.println(vehicle.getMilage());
     vehicle.setServiceIntervals("4500km");
     System.out.println(vehicle.getServiceIntervals());
     vehicle.setServiceCost(12000.0f);
     System.out.println(vehicle.getServiceCost());

     Vehicle vehicle1=new Vehicle();
     System.out.println(vehicle1.getName());
     vehicle1.setName("Suburu");
     System.out.println(vehicle1.getName());
     System.out.println(vehicle1.getPrice());
     vehicle1.setPrice(500000.2f);
     System.out.println(vehicle1.getPrice());
     vehicle1.setCapacity(4000);
     System.out.println(vehicle1.getCapacity());
     vehicle1.setFeatures("4x4");
     System.out.println(vehicle1.getFeatures());
     vehicle1.setMilage(12.3f);
     System.out.println(vehicle1.getMilage());
     vehicle1.setServiceIntervals("4500km");
     System.out.println(vehicle1.getServiceIntervals());
     vehicle1.setServiceCost(12000.0f);
     System.out.println(vehicle1.getServiceCost());

     Vehicle vehicle2=new Vehicle();
     System.out.println(vehicle2.getName());
     vehicle2.setName("Suzuki");
     System.out.println(vehicle2.getName());
     System.out.println(vehicle2.getPrice());
     vehicle2.setPrice(500000.2f);
     System.out.println(vehicle2.getPrice());
     vehicle2.setCapacity(4000);
     System.out.println(vehicle2.getCapacity());
     vehicle2.setFeatures("4x4");
     System.out.println(vehicle2.getFeatures());
     vehicle2.setMilage(12.3f);
     System.out.println(vehicle2.getMilage());
     vehicle2.setServiceIntervals("4500km");
     System.out.println(vehicle2.getServiceIntervals());
     vehicle2.setServiceCost(12000.0f);
     System.out.println(vehicle2.getServiceCost());

     Vehicle vehicle3=new Vehicle();
     System.out.println(vehicle3.getName());
     vehicle3.setName("Honda");
     System.out.println(vehicle3.getName());
     System.out.println(vehicle3.getPrice());
     vehicle3.setPrice(500000.2f);
     System.out.println(vehicle3.getPrice());
     vehicle3.setCapacity(4000);
     System.out.println(vehicle3.getCapacity());
     vehicle3.setFeatures("4x4");
     System.out.println(vehicle3.getFeatures());
     vehicle3.setMilage(12.3f);
     System.out.println(vehicle3.getMilage());
     vehicle3.setServiceIntervals("4500km");
     System.out.println(vehicle3.getServiceIntervals());
     vehicle3.setServiceCost(12000.0f);
     System.out.println(vehicle3.getServiceCost());

     Vehicle vehicle4=new Vehicle();
     System.out.println(vehicle4.getName());
     vehicle4.setName("Hyundai");
     System.out.println(vehicle4.getName());
     System.out.println(vehicle4.getPrice());
     vehicle4.setPrice(500000.2f);
     System.out.println(vehicle4.getPrice());
     vehicle4.setCapacity(4000);
     System.out.println(vehicle4.getCapacity());
     vehicle4.setFeatures("4x4");
     System.out.println(vehicle4.getFeatures());
     vehicle4.setMilage(12.3f);
     System.out.println(vehicle4.getMilage());
     vehicle4.setServiceIntervals("4500km");
     System.out.println(vehicle4.getServiceIntervals());
     vehicle4.setServiceCost(12000.0f);
     System.out.println(vehicle4.getServiceCost());

     Vehicle vehicle5=new Vehicle();
     System.out.println(vehicle5.getName());
     vehicle5.setName("Kia");
     System.out.println(vehicle5.getName());
     System.out.println(vehicle5.getPrice());
     vehicle5.setPrice(500000.2f);
     System.out.println(vehicle5.getPrice());
     vehicle5.setCapacity(4000);
     System.out.println(vehicle5.getCapacity());
     vehicle5.setFeatures("4x4");
     System.out.println(vehicle5.getFeatures());
     vehicle5.setMilage(12.3f);
     System.out.println(vehicle5.getMilage());
     vehicle5.setServiceIntervals("4500km");
     System.out.println(vehicle5.getServiceIntervals());
     vehicle5.setServiceCost(12000.0f);
     System.out.println(vehicle5.getServiceCost());

     Vehicle vehicle6=new Vehicle();
     System.out.println(vehicle6.getName());
     vehicle6.setName("Ford");
     System.out.println(vehicle6.getName());
     System.out.println(vehicle6.getPrice());
     vehicle6.setPrice(500000.2f);
     System.out.println(vehicle6.getPrice());
     vehicle6.setCapacity(4000);
     System.out.println(vehicle6.getCapacity());
     vehicle6.setFeatures("4x4");
     System.out.println(vehicle6.getFeatures());
     vehicle6.setMilage(12.3f);
     System.out.println(vehicle6.getMilage());
     vehicle6.setServiceIntervals("4500km");
     System.out.println(vehicle6.getServiceIntervals());
     vehicle6.setServiceCost(12000.0f);
     System.out.println(vehicle6.getServiceCost());

     Vehicle vehicle7=new Vehicle();
     System.out.println(vehicle7.getName());
     vehicle7.setName("Land Rower");
     System.out.println(vehicle7.getName());
     System.out.println(vehicle7.getPrice());
     vehicle7.setPrice(500000.2f);
     System.out.println(vehicle7.getPrice());
     vehicle7.setCapacity(4000);
     System.out.println(vehicle7.getCapacity());
     vehicle7.setFeatures("4x4");
     System.out.println(vehicle7.getFeatures());
     vehicle7.setMilage(12.3f);
     System.out.println(vehicle7.getMilage());
     vehicle7.setServiceIntervals("4500km");
     System.out.println(vehicle7.getServiceIntervals());
     vehicle7.setServiceCost(12000.0f);
     System.out.println(vehicle7.getServiceCost());

     Vehicle vehicle8=new Vehicle();
     System.out.println(vehicle8.getName());
     vehicle8.setName("Marithi");
     System.out.println(vehicle8.getName());
     System.out.println(vehicle8.getPrice());
     vehicle8.setPrice(500000.2f);
     System.out.println(vehicle8.getPrice());
     vehicle8.setCapacity(4000);
     System.out.println(vehicle8.getCapacity());
     vehicle8.setFeatures("4x4");
     System.out.println(vehicle8.getFeatures());
     vehicle8.setMilage(12.3f);
     System.out.println(vehicle8.getMilage());
     vehicle8.setServiceIntervals("4500km");
     System.out.println(vehicle8.getServiceIntervals());
     vehicle8.setServiceCost(12000.0f);
     System.out.println(vehicle8.getServiceCost());

     Vehicle vehicle9=new Vehicle();
     System.out.println(vehicle9.getName());
     vehicle9.setName("Volkswagen");
     System.out.println(vehicle9.getName());
     System.out.println(vehicle9.getPrice());
     vehicle9.setPrice(500000.2f);
     System.out.println(vehicle9.getPrice());
     vehicle9.setCapacity(4000);
     System.out.println(vehicle9.getCapacity());
     vehicle9.setFeatures("4x4");
     System.out.println(vehicle9.getFeatures());
     vehicle9.setMilage(12.3f);
     System.out.println(vehicle9.getMilage());
     vehicle9.setServiceIntervals("4500km");
     System.out.println(vehicle9.getServiceIntervals());
     vehicle9.setServiceCost(12000.0f);
     System.out.println(vehicle9.getServiceCost());

 }
}