class WorkerRunner {
    public static void main(String args[]) {
        Worker worker = new Worker();
        System.out.println(worker.getName());
        worker.setName("Ramesh");
        System.out.println(worker.getName());
        System.out.println(worker.getSalary());
        worker.setSalary(25000.2f);
        System.out.println(worker.getSalary());
        worker.setHoursPerWeek(48);
        System.out.println(worker.getHoursPerWeek());
        worker.setSkill("Electrician");
        System.out.println(worker.getSkill());
        worker.setExperience(4.3f);
        System.out.println(worker.getExperience());
        worker.setShiftTimings("9 AM - 6 PM");
        System.out.println(worker.getShiftTimings());
        worker.setOvertimeRate(200.0f);
        System.out.println(worker.getOvertimeRate());

        Worker worker1 = new Worker();
        System.out.println(worker1.getName());
        worker1.setName("Suresh");
        System.out.println(worker1.getName());
        System.out.println(worker1.getSalary());
        worker1.setSalary(27000.5f);
        System.out.println(worker1.getSalary());
        worker1.setHoursPerWeek(50);
        System.out.println(worker1.getHoursPerWeek());
        worker1.setSkill("Welder");
        System.out.println(worker1.getSkill());
        worker1.setExperience(5.1f);
        System.out.println(worker1.getExperience());
        worker1.setShiftTimings("9 AM - 6 PM");
        System.out.println(worker1.getShiftTimings());
        worker1.setOvertimeRate(200.0f);
        System.out.println(worker1.getOvertimeRate());

        Worker worker2 = new Worker();
        System.out.println(worker2.getName());
        worker2.setName("Mahesh");
        System.out.println(worker2.getName());
        System.out.println(worker2.getSalary());
        worker2.setSalary(28000.0f);
        System.out.println(worker2.getSalary());
        worker2.setHoursPerWeek(45);
        System.out.println(worker2.getHoursPerWeek());
        worker2.setSkill("Plumber");
        System.out.println(worker2.getSkill());
        worker2.setExperience(3.8f);
        System.out.println(worker2.getExperience());
        worker2.setShiftTimings("9 AM - 6 PM");
        System.out.println(worker2.getShiftTimings());
        worker2.setOvertimeRate(200.0f);
        System.out.println(worker2.getOvertimeRate());

        Worker worker3 = new Worker();
        System.out.println(worker3.getName());
        worker3.setName("Ganesh");
        System.out.println(worker3.getName());
        System.out.println(worker3.getSalary());
        worker3.setSalary(26000.0f);
        System.out.println(worker3.getSalary());
        worker3.setHoursPerWeek(46);
        System.out.println(worker3.getHoursPerWeek());
        worker3.setSkill("Painter");
        System.out.println(worker3.getSkill());
        worker3.setExperience(2.9f);
        System.out.println(worker3.getExperience());
        worker3.setShiftTimings("9 AM - 6 PM");
        System.out.println(worker3.getShiftTimings());
        worker3.setOvertimeRate(200.0f);
        System.out.println(worker3.getOvertimeRate());

        Worker worker4 = new Worker();
        System.out.println(worker4.getName());
        worker4.setName("Dinesh");
        System.out.println(worker4.getName());
        System.out.println(worker4.getSalary());
        worker4.setSalary(29000.0f);
        System.out.println(worker4.getSalary());
        worker4.setHoursPerWeek(44);
        System.out.println(worker4.getHoursPerWeek());
        worker4.setSkill("Carpenter");
        System.out.println(worker4.getSkill());
        worker4.setExperience(4.5f);
        System.out.println(worker4.getExperience());
        worker4.setShiftTimings("9 AM - 6 PM");
        System.out.println(worker4.getShiftTimings());
        worker4.setOvertimeRate(200.0f);
        System.out.println(worker4.getOvertimeRate());

        Worker worker5 = new Worker();
        System.out.println(worker5.getName());
        worker5.setName("Lokesh");
        System.out.println(worker5.getName());
        System.out.println(worker5.getSalary());
        worker5.setSalary(30000.0f);
        System.out.println(worker5.getSalary());
        worker5.setHoursPerWeek(47);
        System.out.println(worker5.getHoursPerWeek());
        worker5.setSkill("Fitter");
        System.out.println(worker5.getSkill());
        worker5.setExperience(6.0f);
        System.out.println(worker5.getExperience());
        worker5.setShiftTimings("9 AM - 6 PM");
        System.out.println(worker5.getShiftTimings());
        worker5.setOvertimeRate(200.0f);
        System.out.println(worker5.getOvertimeRate());

        Worker worker6 = new Worker();
        System.out.println(worker6.getName());
        worker6.setName("Naresh");
        System.out.println(worker6.getName());
        System.out.println(worker6.getSalary());
        worker6.setSalary(32000.0f);
        System.out.println(worker6.getSalary());
        worker6.setHoursPerWeek(48);
        System.out.println(worker6.getHoursPerWeek());
        worker6.setSkill("Mechanic");
        System.out.println(worker6.getSkill());
        worker6.setExperience(7.0f);
        System.out.println(worker6.getExperience());
        worker6.setShiftTimings("9 AM - 6 PM");
        System.out.println(worker6.getShiftTimings());
        worker6.setOvertimeRate(200.0f);
        System.out.println(worker6.getOvertimeRate());

        Worker worker7 = new Worker();
        System.out.println(worker7.getName());
        worker7.setName("Rajesh");
        System.out.println(worker7.getName());
        System.out.println(worker7.getSalary());
        worker7.setSalary(31000.0f);
        System.out.println(worker7.getSalary());
        worker7.setHoursPerWeek(42);
        System.out.println(worker7.getHoursPerWeek());
        worker7.setSkill("Mason");
        System.out.println(worker7.getSkill());
        worker7.setExperience(5.7f);
        System.out.println(worker7.getExperience());
        worker7.setShiftTimings("9 AM - 6 PM");
        System.out.println(worker7.getShiftTimings());
        worker7.setOvertimeRate(200.0f);
        System.out.println(worker7.getOvertimeRate());

        Worker worker8 = new Worker();
        System.out.println(worker8.getName());
        worker8.setName("Raju");
        System.out.println(worker8.getName());
        System.out.println(worker8.getSalary());
        worker8.setSalary(29500.0f);
        System.out.println(worker8.getSalary());
        worker8.setHoursPerWeek(49);
        System.out.println(worker8.getHoursPerWeek());
        worker8.setSkill("Electrician");
        System.out.println(worker8.getSkill());
        worker8.setExperience(6.5f);
        System.out.println(worker8.getExperience());
        worker8.setShiftTimings("9 AM - 6 PM");
        System.out.println(worker8.getShiftTimings());
        worker8.setOvertimeRate(200.0f);
        System.out.println(worker8.getOvertimeRate());

        Worker worker9 = new Worker();
        System.out.println(worker9.getName());
        worker9.setName("Shyam");
        System.out.println(worker9.getName());
        System.out.println(worker9.getSalary());
        worker9.setSalary(30500.0f);
        System.out.println(worker9.getSalary());
        worker9.setHoursPerWeek(46);
        System.out.println(worker9.getHoursPerWeek());
        worker9.setSkill("Plumber");
        System.out.println(worker9.getSkill());
        worker9.setExperience(4.8f);
        System.out.println(worker9.getExperience());
        worker9.setShiftTimings("9 AM - 6 PM");
        System.out.println(worker9.getShiftTimings());
        worker9.setOvertimeRate(200.0f);
        System.out.println(worker9.getOvertimeRate());
    }
}
